config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects do
    resources :team_members, only: %i[new create edit update destroy]
    resources :milestones, only: %i[new create edit update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  belongs_to :project

  validates :title, :due_date, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :team_members, dependent: :destroy
    has_many :milestones, dependent: :destroy
  
    validates :name, :start_date, :due_date, :priority, :status, presence: true
    validates :priority, inclusion: { in: %w[High Medium Low] }
    validates :status, inclusion: { in: %w[Not\ Started In\ Progress Completed] }
  end
  

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :project

  validates :name, :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: %i[edit update destroy]

  def new
    @milestone = Milestone.new(project_id: params[:project_id])
  end

  def create
    @milestone = Milestone.new(milestone_params)
    if @milestone.save
      redirect_to project_path(@milestone.project), notice: 'Milestone was successfully added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @milestone.update(milestone_params)
      redirect_to project_path(@milestone.project), notice: 'Milestone was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    project = @milestone.project
    @milestone.destroy
    redirect_to project_path(project), notice: 'Milestone was successfully removed.'
  end

  private

  def set_milestone
    @milestone = Milestone.find(params[:id])
  end

  def milestone_params
    params.require(:milestone).permit(:title, :description, :due_date, :completed, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show
    @team_members = @project.team_members
    @milestones = @project.milestones
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully deleted.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :start_date, :due_date, :priority, :status)
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: %i[edit update destroy]

  def new
    @team_member = TeamMember.new(project_id: params[:project_id])
  end

  def create
    @team_member = TeamMember.new(team_member_params)
    if @team_member.save
      redirect_to project_path(@team_member.project), notice: 'Team member was successfully added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @team_member.update(team_member_params)
      redirect_to project_path(@team_member.project), notice: 'Team member was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    project = @team_member.project
    @team_member.destroy
    redirect_to project_path(project), notice: 'Team member was successfully removed.'
  end

  private

  def set_team_member
    @team_member = TeamMember.find(params[:id])
  end

  def team_member_params
    params.require(:team_member).permit(:name, :role, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project Management App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/milestones/_form.html.erb
<%= form_with(model: milestone) do |form| %>
  <% if milestone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
        <% milestone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/milestones/_milestone.html.erb
<div id="<%= dom_id milestone %>">
  <p>
    <strong>Title:</strong>
    <%= milestone.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= milestone.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= milestone.due_date %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= milestone.project_id %>
  </p>

</div>

app/views/milestones/edit.html.erb
<% content_for :title, "Editing milestone" %>

<h1>Editing milestone</h1>

<%= render "form", milestone: @milestone %>

<br>

<div>
  <%= link_to "Show this milestone", @milestone %> |
  <%= link_to "Back to milestones", milestones_path %>
</div>

app/views/milestones/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Milestones" %>

<h1>Milestones</h1>

<div id="milestones">
  <% @milestones.each do |milestone| %>
    <%= render milestone %>
    <p>
      <%= link_to "Show this milestone", milestone %>
    </p>
  <% end %>
</div>

<%= link_to "New milestone", new_milestone_path %>

app/views/milestones/new.html.erb
<% content_for :title, "New milestone" %>

<h1>New milestone</h1>

<%= render "form", milestone: @milestone %>

<br>

<div>
  <%= link_to "Back to milestones", milestones_path %>
</div>

app/views/milestones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @milestone %>

<div>
  <%= link_to "Edit this milestone", edit_milestone_path(@milestone) %> |
  <%= link_to "Back to milestones", milestones_path %>

  <%= button_to "Destroy this milestone", @milestone, method: :delete %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.text_field :priority %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= project.start_date %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= project.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= project.priority %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/team_members/_form.html.erb
<%= form_with(model: team_member) do |form| %>
  <% if team_member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
        <% team_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/team_members/_team_member.html.erb
<div id="<%= dom_id team_member %>">
  <p>
    <strong>Name:</strong>
    <%= team_member.name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= team_member.role %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= team_member.project_id %>
  </p>

</div>

app/views/team_members/edit.html.erb
<% content_for :title, "Editing team member" %>

<h1>Editing team member</h1>

<%= render "form", team_member: @team_member %>

<br>

<div>
  <%= link_to "Show this team member", @team_member %> |
  <%= link_to "Back to team members", team_members_path %>
</div>

app/views/team_members/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Team members" %>

<h1>Team members</h1>

<div id="team_members">
  <% @team_members.each do |team_member| %>
    <%= render team_member %>
    <p>
      <%= link_to "Show this team member", team_member %>
    </p>
  <% end %>
</div>

<%= link_to "New team member", new_team_member_path %>

app/views/team_members/new.html.erb
<% content_for :title, "New team member" %>

<h1>New team member</h1>

<%= render "form", team_member: @team_member %>

<br>

<div>
  <%= link_to "Back to team members", team_members_path %>
</div>

app/views/team_members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @team_member %>

<div>
  <%= link_to "Edit this team member", edit_team_member_path(@team_member) %> |
  <%= link_to "Back to team members", team_members_path %>

  <%= button_to "Destroy this team member", @team_member, method: :delete %>
</div>